version: '3.0'

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: thesis
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "127.0.0.1:5673:5672"
      - "127.0.0.1:15673:15672"
