on:
  push:
    branches: ['main', '*.*.x']
  pull_request: ~

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:alpine
        ports:
          - "5672:5672"
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        php: ["8.3"]
        dependencies: ["locked", "lowest", "highest"]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-file: development
          tools: composer:v2
          extensions: pcntl
          ini-values: disable_functions=pcntl_fork
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
          dependency-versions: ${{ matrix.dependencies }}
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH || '{}' }}
      - run: THESIS_AMQP_DSN="amqp://guest:guest@127.0.0.1:5672/?tcp_nodelay=true" composer test -- --colors=always
